name: Create new content

on:
  workflow_dispatch:
    inputs:
      path:
        description: 'Content path to root folder'
        required: true

jobs:
  create-new-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: andrijasinski/test-cms
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./test-cms
          fetch-depth: 0

      - name: Print GitHub context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Create default content structure
        env:
          TRIGGERING_AUTHOR: ${{ github.triggering_actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONTENT_PATH: ${{ github.event.inputs.path }}
        run: |
          echo "Starting script"
          chmod +x "${GITHUB_WORKSPACE}/test-cms/.github/createNewContent.sh"
          ${GITHUB_WORKSPACE}/test-cms/.github/createNewContent.sh
          echo "Script finished"
