# This is a basic workflow to help you get started with Actions

name: PR structure check

# Controls when the workflow will run
on:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
#       - uses: Stockopedia/action-get-changed-files@v1
#         id: changed-files
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           ignore: "**/+(.github)"
#           foldersOnly: true 
#           format: csv
#       - name: Echo changed files
#         run: echo ${{ steps.get_changed.outputs.changed }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files_ignore: .github/** # Alternatively using: `docs`

      - name: Run step if any other js file(s) change
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "List all the files that have changed: ${{ steps.changed-files }}"
