name: PR structure check

on:
  pull_request:

jobs:
  check-pr:
    runs-on: ubuntu-latest
    outputs:
      checkoutput: ${{ steps.check.outputs.bad_dirs }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Print GitHub context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files_ignore: .github/**
          separator: ","

      - name: Check changed files
        run: |
          echo "changed: ${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Check structure
        id: check
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          BAD_DIRS_PATH: /home/runner/work/test-cms/test-cms/.github/bad_dirs.txt
        run: |
          if python ${GITHUB_WORKSPACE}/.github/checkPrStructure.py; then
              echo ok
          else
              echo "bad_dirs=$(cat ${GITHUB_WORKSPACE}/.github/bad_dirs.txt)" >> $GITHUB_ENV
              exit 1
          fi

      - name: Comment on PR
        if: failure()
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: prcheck
          mode: recreate
          message: |
            Not all directory names are following requirements of [ISO 639-1 language codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) or [ISO 639-1 language codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) & [ISO3166-1 alpha-2 country codes](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements)!
            Example of allowed directory names: `en` or `en-GB`
            Bad directories: ${{ env.bad_dirs }}

#       Commit SHA: ${{ github.event.pull_request.head.sha }}
        
