name: PR structure check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
#         with:
#           repository: andrijasinski/test-cms
#           token: ${{ secrets.GITHUB_TOKEN }}
#           path: ./test-cms
#           fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files_ignore: .github/**
          separator: ","

      - name: Check changed files
        run: |
          echo "changed: ${{ toJson(steps.changed-files.outputs.all_changed_files) }}"


      - name: Check github workspace
        run: |
          ls "${GITHUB_WORKSPACE}"

      - name: Check structure
        env:
          CHANGED_FILES: ${{ toJson(steps.changed-files.outputs.all_changed_files) }}
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/checkPrStructure.py"
          python ${GITHUB_WORKSPACE}/.github/checkPrStructure.py
