name: PR structure check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files_ignore: .github/**
          separator: ","

      - name: Check changed files
        run: |
          echo "changed: ${{ toJson(steps.changed-files.outputs.all_changed_files) }}"

      - name: Check changed files
        env:
          CHANGED_FILES: ${{ toJson(steps.changed-files.outputs.all_changed_files) }}
        run: |
          chmod +x "${GITHUB_WORKSPACE}/test-cms/.github/checkPrStructure.py"
          python ${GITHUB_WORKSPACE}/test-cms/.github/checkPrStructure.py
