name: PR structure check

on:
  pull_request:

jobs:
  check-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files_ignore: .github/**
          separator: ","

      - name: Check changed files
        run: |
          echo "changed: ${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Check structure
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: python ${GITHUB_WORKSPACE}/.github/checkPrStructure.py

      - name: Comment on PR
        if: failure()
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Not all directory names are following requirements of ISO 639-1 language codes or ISO 639-1 language codes & ISO3166-1 alpha-2 country codes (f.e `en` or `en-GB`)! :eyes:
        
